name: dheeraj test
description: just to check and get familiarize
inputs:
  name:
    description: my name
    required: true
  echo:
    description: a boolean flag
    required: true

runs:
  using: composite
  steps:
    - name: Perform operation
      shell: python
      run: |
        import os

        if os.getenv('INPUT_ECHO') == 'true':
            operation = 'echo'
        else:
            operation = 'dontecho'

        # Set the environment variable
        os.environ['operation'] = operation

    - name: Print operation
      shell: python
      run: |
        import os

        operation = os.getenv('operation')
        name = os.getenv('INPUT_NAME')

        print(f"{operation}ing your name: {name}")
