name: dheeraj test
description: just to check and get familiarize
inputs:
  name:
    description: my name
    required: true
  echo:
    description: a boolean flag
    required: true
    default: false

runs:
  using: composite
  steps:
    - name: Perform operation
      shell: bash
      run: |
        if [[ "${{ inputs.echo }}" == "true" ]]; then
          echo "operation=echo" >> $GITHUB_ENV
        else
          echo "operation=dontecho" >> $GITHUB_ENV
        fi

    - name: Print operation
      shell: bash
      run: |
        echo "${{ env.operation }}ing your name: ${{ inputs.name }}"
