name: dheeraj test
description: just to check and get familiarize
inputs:
  name:
    description: my name
    required: true
  echo:
    description: a boolean flag
    required: true

runs:
  using: composite
  steps:
    - name: testing powershell
      shell: powershell
      run: |
        if($${{ inputs.echo }}) {
          $cmd="echo ${{ inputs.name }}"
        }else {
          $cmd="echo 'Nothing to echo'"
        }
        echo "::set-output name=cmd::$cmd"
    - name: Perform operation
      shell: powershell
      run: |
        $command=${{ env.cmd }}
        echo $command

    # - name: Print operation
    #   shell: python
    #   run: |
    #     import os

    #     operation = os.getenv('operation')
    #     name = os.getenv('INPUT_NAME')

    #     print(f"{operation}ing your name: {name}")
