name: dheeraj test
description: just to check and get familiarize
inputs:
  name:
    description: my name
    required: true
  echo:
    description: a boolean flag
    required: true

runs:
  using: composite
  steps:
    - name: testing powershell
      if: ${{ runner.os == 'Windows'}}
      id: setEnv
      shell: powershell
      run: |
        if($${{ inputs.echo }}) {
          $cmd="echo ${{ inputs.name }}"
        }else {
          $cmd="echo 'Nothing to echo'"
        }
        echo "::set-output name=cmd::$cmd"

    # - name: tree workspace
    #   if: ${{ env.ACTIONS_STEP_DEBUG }}==true || ${{ env.ACTIONS_RUNNER_DEBUG }}==true  
    #   shell: powershell
    #   run: |
    #     tree ${{ github.workspace }}
      
    - name: Perform operation
      if: ${{ runner.os == 'Windows'}}
      env: 
        CMD: ${{ steps.setEnv.outputs.cmd }}
      shell: powershell
      run: |
        $command=${{ env.CMD }}
        echo $command

    - name: Checkout code
      uses: actions/checkout@v2
      with:
          path: repo

    - name: Run Python script
      if: ${{ runner.os == 'Windows'}}
      id: run
      shell: powershell
      run: |
        $output=Invoke-Expression -Command "python ${{ github.workspace }}/repo/test.py"
        echo "::set-output name=python_output::$output"

    - name: Run Python script
      if: ${{ runner.os == 'Linux'}}
      id: run1
      shell: bash
      run: |
        output="python3 ${{ github.workspace }}/repo/test.py"
        echo "::set-output name=python_output::$output"

    - name: Use Python output
      if: ${{ runner.os == 'Windows'}}
      shell: powershell
      run: |
        echo "Python script output: ${{ steps.run.outputs.python_output }}"

    - name: Use Python output
      if: ${{ runner.os == 'Linux'}}
      shell: bash
      run: |
        echo "Python script output: ${{ steps.run1.outputs.python_output }}"
