name: Context
on: [push, pull_request]

jobs:
  svn:
    runs-on: ubuntu-20.04
    steps:
      - name: version check
        env:
          USERNAME: dheeraj
          PASSWORD: xyz@1234
        run: |
          pwd
          svn --version
          $username=env.USERNAME
          $password=env.PASSWORD  
          echo $username
          echo $password
  functions: 
    runs-on: ubuntu-20.04
    steps:
      - name: dump
        env:
          WHAT_TO_CHECK: ${{ secrets.TEST}}
        run: |
          echo ${{ contains( 'hello', '11' ) }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', '1o' ) }}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', '!' ) }}
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.TEST }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.TEST}} | sed 's/./& /g' 
  one:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        if: always()
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"