name: shell commands
run-name: ${{github.actor}} is learning the Github Actions
on: [pull_request]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Dheeraj learning github-actions"
      - name: multiliine script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          import datetime
          now = datetime.datetime.now()
          print(platform.processor())
          print("The current datetime is: ",now)
        shell: python

  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
      - name: Python commands 
        run: |
          import platform
          import datetime
          now = datetime.datetime.now()
          print(platform.processor())
          print("The current datetime is: ",now)
        shell: python