name: Test
on: [push, pull_request]


jobs:
  run-github-actions: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: check checkout
        run:
          ls -la ${{ github.workspace }}
        
      - name: testing  
        run: |
          cd  ${{ github.workspace }}
          RECIPE=${{ github.workspace }}/reciepe.json
          declare -a jsonArray
          cat "$RECIPE" | jq -c '.[]' | while IFS= read -r element; do
            TARGET=$(echo "$element" | jq -r '.target')
            TARGETADDRESS=$(echo "$element" | jq -r '.targetAddress')
            jsonObject=$(jq -n --arg target "${{ github.workspace }}/$TARGET" --arg targetAddress "$TARGETADDRESS" '{target: $target, targetAddress: $targetAddress}')
            jsonArray+=$jsonObject
            echo $jsonObject
            echo $TARGET
            echo $TARGETADDRESS
          done
          echo $jsonArray
          echo Dheeraj
