name: Test
on: [push, pull_request]


jobs:
  run-github-actions: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: check checkout
        run:
          ls -la ${{ github.workspace }}
        
      - name: using python
        shell: python
        run: |
          import json
          file_path = '${{ github.workspace }}/reciepe.json'
          with open(file_path, 'r') as file:
              data = json.load(file)
          print(data)
          for element in data:
              element['target'] = '${{ github.workspace }}' + '/' + element['target']
          print(data)
          
      - name: testing  
        run: |
          cd  ${{ github.workspace }}
          RECIPE=${{ github.workspace }}/reciepe.json
          jsonArray=()
          cat "$RECIPE" | jq -c '.[]' | while IFS= read -r element; do
            TARGET=$(echo "$element" | jq -r '.target')
            TARGETADDRESS=$(echo "$element" | jq -r '.targetAddress')
            jsonObject=$(jq -n --arg target "${{ github.workspace }}/$TARGET" --arg targetAddress "$TARGETADDRESS" '{target: $target, targetAddress: $targetAddress}')
            jsonArray+=("$jsonObject")
            echo $jsonObject
            echo $TARGET
            echo $TARGETADDRESS
          done
          echo "contents of jsonArray"
