name: build, test and deploy installer package test

on:
  push

env:
  name: "samyuktha"
  
jobs:

  Read_input:

    runs-on: [ windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: uploadAction

      - name: run action
        id: dheeraj
        uses: ./uploadAction
        with:
          name: Dheeraj
          echo: true

      - name: check output
        run: echo ${{ steps.dheeraj.outputs.my_dict }}

      - name: exit or not
        id: some
        run: exit 0
        continue-on-error: true 

      - name: change env name
        if: steps.some.outcome == 'success'
        run: echo "Modifying MY_VARIABLE in this step"
        env:
          name: "Dheeraj"

      - name: echo name
        run: echo "Hello $env:name!"
        
