name: Test
on: [push, pull_request]


jobs:
  run-github-actions: 
    runs-on: windows-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: check checkout
        run:
          ls -la ${{ github.workspace }}
        
      - name: testing  
        run: |
          cd  ${{ github.workspace }}/github-actions-first
          echo reciepe.json
