name: Test
on: [push, pull_request]


jobs:
  run-github-actions: 
    runs-on: windows-latest 
    env: 
      WORKSAPCE: ${{ github.workspace }} 
    steps:
      - name: testing variables 
        run: |
          echo $WORKSPACE