name: Test
on: [push, pull_request]
env: 
  WORKSAPCE: ${{ github.workspace }}

jobs:
  run-github-actions: 
    runs-on: windows-latest  
    steps:
      - name: testing variables 
        run: |
          echo $WORKSPACE