name: build, test and deploy installer package test

on:
  push

jobs:

  Read_input:

    runs-on: [ windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: uploadAction

      - name: tree workspace
        if: ${{ env.ACTIONS_STEP_DEBUG }}
        shell: powershell
        run: |
          tree ${{ github.workspace }} 
  
