name: Test
on: push


jobs:
  job-a:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: run job a
        run: |
          echo "running job a somehwere"
          exit 1

  job-b:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: run job B 
        run: |
          echo "running job a somehwere"
          exit 0

  job-ab:
    name: Job AB
    runs-on: ubuntu-latest
    needs: [ job-a, job-b ]
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    steps:
      - name: run job ab
        run: |
          echo "running job a somehwere"
          exit 0
