name: build, test and deploy installer package test

on:
  push
  
jobs:
  Read_input:
    env:
      name: "samyuktha"
    runs-on: [ windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: uploadAction

      - name: run action
        id: dheeraj
        uses: ./uploadAction
        with:
          name: Dheeraj
          echo: true

      - name: check output
        run: echo ${{ steps.dheeraj.outputs.my_dict }}

      - name: exit or not
        id: some
        run: exit 1
        continue-on-error: true 

      - name: change env name
        run: echo "name=Dheeraj" >> $GITHUB_ENV
        if: steps.some.outcome == 'success'

      - name: Create JSON file
        run: |
          if ('${{ steps.some.outcome }}' -eq 'success'){
            $jsonObject1 = @{
                    operation = "copy"
                    source = "vwos-tools-generic-exchange/$package"
                    target = "vwos-tools-generic-playground/$package"
            }
          }else{
            $jsonObject1 = @{
                    operation = "paste"
                    source = "vwos-tools-generic-exchange/$package"
                    target = "vwos-tools-generic-playground/$package"
            }
          }
          $jsonContent = $jsonObject1 | ConvertTo-Json
          $jsonContent | Set-Content -Path ".\recipe.json"
              

      - name: Display JSON content
        run: type .\recipe.json
        
