name: build, test and deploy installer package test

on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - master

jobs:

  Read_SupportedOS:

    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read SupportedOS from JSON
        id: read-supportedos
        run: |
          file_path="${{ github.workspace }}/github-actions-first/${{ github.head_ref }}/installCFG.json"
          if [[ -s "$file_path" ]]; then
            supported_os=$(cat "$file_path" | jq -r '.SupportedOS[]')
          else
            supported_os='["win10", "win22"]'
          fi
          echo "::set-output name=supported-os::$supported_os"


  Test_Deploy_QA_Package:

    needs: Read_SupportedOS
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: [ ubuntu-latest ]

    steps:
      - name: echo that PR opened
        run: |
          echo "A new PR is opened"
          echo " ${{ steps.read-supportedos.outputs.supported-os }} "


  Test_Deploy_Release_Package:

    needs: Read_SupportedOS
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'master' }}
    runs-on: [ ubuntu-latest ]

    steps:
      - name: echo that PR opened
        run: |
          echo "A new PR is opened"
