name: Test
on: push


jobs:
  run-github-actions: 
    runs-on: windows-latest 
    steps:
      - name: testing variables 
        run: |
          echo ${{ github.workspace }} 
  echo-hello-world:
     runs-on: windows-latest 
     needs: run-github-actions
     if: ${{ success(needs.run-github-actions) }}
     steps:
       - name: echo Hello World
         run: |
           echo "Hello world"
